### ISSUE TITLE
解压后打开出现错误代码，请指导！

### ISSUE THREAD

**Issue by shixianzhang** [157459387/xxqg_enter#7]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxqg_enter.py", line 209, in <module>
  File "xxqg_enter.py", line 42, in __init__
  File "Xxqg.py", line 991, in get_xxqg
  File "singleton.py", line 13, in __call__
  File "Xxqg.py", line 39, in __init__
NameError: name 'exit' is not defined
[10472] Failed to execute script 'xxqg_enter' due to unhandled exception!

**Comment by 157459387** [comment]
你下载的压缩包？最新的不是压缩包，直接从git拉就行了，压缩包形式的很老了。
